# Generated by Django 2.2.4 on 2019-08-28 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='commuUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.TextField(max_length='64', unique='True', verbose_name='사용자 이름')),
                ('userEmail', models.TextField(max_length='64', unique='True', verbose_name='사용자 Email')),
                ('userPassword', models.TextField(max_length='64', unique='True', verbose_name='사용자 비밀번호')),
            ],
        ),
    ]
