# Generated by Django 2.2.4 on 2019-08-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comuUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=32, verbose_name='사용자명')),
                ('userPassword', models.CharField(max_length=32, verbose_name='사용자암호')),
                ('signUpDate', models.DateField(auto_now=True, verbose_name='가입일')),
            ],
            options={
                'db_table': 'comuUser',
            },
        ),
    ]
