# Generated by Django 2.2.4 on 2019-08-22 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comuUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comuuser',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
        migrations.AddField(
            model_name='comuuser',
            name='userEmail',
            field=models.EmailField(default=django.utils.timezone.now, max_length=60, verbose_name='이메일'),
            preserve_default=False,
        ),
    ]
