# Generated by Django 2.2.4 on 2019-09-09 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20190909_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comuUser.CommuUser', verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='targetPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comuUser.CommuUser', verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.category'),
        ),
    ]
